# Generated by Django 4.2.4 on 2023-08-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('products_id', models.AutoField(primary_key=True, serialize=False)),
                ('products_name', models.CharField(max_length=100)),
                ('products_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('products_description', models.TextField()),
                ('products_image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
