# Generated by Django 4.2.4 on 2023-08-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_products_rating_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='products_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
