# Generated by Django 4.2.4 on 2023-08-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_products_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
            preserve_default=False,
        ),
    ]
