# Generated by Django 4.2.4 on 2023-08-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_review_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
